const activities=[
{id:1,date:'2026',sort:'2026-01-01',title:'SCARS 2026',type:'展会 / 学术会议',group:'exhibition',place:'米兰，意大利',venue:'',purpose:'国际疤痕治疗会议，汇集皮肤科、整形外科和再生医学专家讨论疤痕与创面治疗。',desc:'官网活动页确认 Alma 参加 SCARS 2026 米兰会议。',data:'官网活动页 meta 描述："SCARS 2026 in Milan will unite global experts in dermatology, plastic surgery, and regenerative medicine to explore the latest innovations in scar treatment and wound healing."',audience:'皮肤科医生、整形外科医生、疤痕与创面治疗专家',result:'官网活动页确认参会（2025-07-20 上线）。',focus:'以具体适应症切入专业会议，比综合型展会更容易建立技术认知。',products:'疤痕治疗技术',source:'https://almalasers.com/events/scars-treatment-conference/',confidence:'A · 官网活动页',image:'assets/scars.jpg',scale:'国际专业会议'},
{id:2,date:'01-18',sort:'2026-01-18',title:'Alma Harmony GOOD DESIGN Award 传播',type:'奖项 / 品牌 PR',group:'pr',place:'全球',venue:'官网与国际社媒',purpose:'围绕 Alma Harmony 获得 2025 GOOD DESIGN Award 开展年度获奖传播。',desc:'强调产品设计、操作工作流、临床体验和创新能力。',data:'2025 GOOD DESIGN® Award · 主办方 The Chicago Athenaeum；新闻稿 2026-01-18 发布；Harmony 集成 5 种能量技术；同期交叉获奖：EPDA Healthcare 类 + Harmony Bio-Boost 获 ELLE Tweakments Awards，官方称 Harmony 为"获奖最多的产品线"。',audience:'医生、诊所经营者、经销商与行业媒体',result:'官网新闻稿与 Instagram 同步发布，延长上一年度奖项的传播周期。',focus:'奖项传播是否能够进一步连接临床结果和采购价值。',products:'Alma Harmony',source:'https://almalasers.com/press/alma-harmony-wins-2025-good-design-award-for-outstanding-innovation-and-design-excellence/',confidence:'A · 官网新闻稿（2026-01-18）',image:'assets/longevity.jpg',scale:'全球品牌传播'},
{id:3,date:'01-20 — 01-25',sort:'2026-01-20',title:'Soprano Titanium Special Edition 体验传播',type:'产品 campaign / KOL 内容',group:'campaign',place:'全球',venue:'Instagram Reels',purpose:'通过多位真实体验者短视频推广 Special Edition 脱毛设备的消费体验。',desc:'连续呈现快速、舒适、冷却保护和适配多肤色等卖点。',data:'背景发布新闻稿：SE 版配"提速治疗头"（2025 年官网发布）。',audience:'潜在消费者、诊所客户、美容从业者',result:'多位体验者在六天内连续出镜，形成统一产品体验主题。',focus:'消费者体验内容较强，可进一步观察是否导向诊所预约和销售线索。',products:'Soprano Titanium Special Edition · @bayle_s · @onyedkwe · Isabella',source:'https://www.instagram.com/reel/DTu7QvDlSkz/',confidence:'B+ · 官方 Instagram 连续内容',image:'assets/soprano.jpg',scale:'全球社媒 campaign'},
{id:4,date:'01-29',sort:'2026-01-29',title:'Alma Global Partners Meeting 2026',type:'伙伴会议 / 渠道营销',group:'owned',place:'全球',venue:'',purpose:'面向全球经销商和合作伙伴的年度渠道会议，用于统一策略、分享经验和规划下一阶段。',desc:'伙伴与团队共同复盘、交流打法、庆祝成果并展望下一阶段（含 sessions、side talks 与社交环节）。',data:'官方 Instagram 当日回顾（2026-01-29）："Alma Global Partners Meeting 2026 was a great day of real connection! Partners and teams sat together, shared what works, challenged each other, celebrated wins, and looked ahead..."',audience:'全球经销商、合作伙伴与 Alma 管理团队',result:'官方账号发布当日活动回顾。',focus:'伙伴会与随后 IMCAS 的资源和客户联动。',products:'Alma 全球产品组合 · 全球伙伴',source:'https://www.instagram.com/reel/DUF42ljFIGV/',confidence:'B+ · 官方 Instagram',image:'assets/academy.jpg',scale:'全球伙伴会议'},
{id:5,date:'01-29 — 01-31',sort:'2026-01-29',title:'IMCAS World Congress 2026',type:'展会 / 学术会议',group:'exhibition',place:'巴黎，法国',venue:'IMCAS 会场',purpose:'全球大型医学美容大会，集中接触医生、诊所、媒体和国际经销商。',desc:'参加 IMCAS 全球大会，安排专家主导环节、现场演示与临床病例回顾，并做 Harmony Bio-Boost 现场演示。',data:'第 27 届；第三方报道 400+ 参展企业、2 万+ 医师及业界人士参会；官网新闻稿可核：巴黎 1/29-31、expert-led sessions、live demonstrations、clinical case reviews、Harmony Bio-Boost 现场演示、大会主题 Intelligent Aesthetics。',audience:'皮肤科及整形医生、诊所、媒体、经销商与行业管理者',result:'Alma Harmony、Bio-Boost 和 Hybrid 获得展台、演示与临床内容多触点曝光。',focus:'把展位、私密体验、学术议程和媒体关系放在同一展会中协同。',products:'Alma Harmony · Harmony Bio-Boost · Alma Hybrid',source:'https://almalasers.com/press/alma-showcases-the-future-of-intelligent-aesthetics-at-imcas-world-congress-2026/',confidence:'A · 官网新闻稿（2026-02-03）',image:'assets/imcas.jpg',scale:'全球大型展会'},
{id:6,date:'02-05 — 02-12',sort:'2026-02-05',title:'Welcome to the Aesthetics Clinic',type:'客户案例 / 内容营销',group:'content',place:'英国、意大利、迪拜、西班牙',venue:'四家客户诊所',purpose:'用诊所经营者和医生视角介绍设备如何进入真实诊所工作流。',desc:'连续呈现设备适配、诊所增长、治疗流程和患者体验。',data:'官方 IG 系列四集：Leicester MediSpa（02-05）、Dr. Nicola Ippoliti @biumyitalia（02-09）、L\'Esprit Clinic 迪拜（02-10）、@idmedicinaestetica 西班牙（02-12）。',audience:'诊所经营者、医生、潜在设备采购者',result:'覆盖四家诊所的连续案例内容。',focus:'客户故事具体，但公开内容可进一步增加运营和治疗量数据。',products:'Alma 多平台 · 四家国际诊所',source:'https://www.instagram.com/reel/DUYaXxDgG94/',confidence:'B+ · 官方 Instagram 系列',image:'assets/clinic.jpg',scale:'跨市场客户案例'},
{id:7,date:'02-14',sort:'2026-02-14',title:'Valentine’s Day 品牌传播',type:'节日品牌传播',group:'brand',place:'全球',venue:'Instagram',purpose:'利用情人节与伙伴、诊所和患者进行轻量品牌互动。',desc:'发布节日主题内容，强化温度感和全球社群连接。',audience:'合作伙伴、诊所、患者与社媒关注者',result:'形成单日节日品牌曝光。',focus:'适合作为社群维护内容，不宜与独立获客活动等量评价。',products:'Alma 品牌',source:'https://www.instagram.com/reel/DUuqoARjqyo/',confidence:'B · 官方 Instagram',image:'assets/soprano.jpg',scale:'单日品牌内容'},
{id:8,date:'02-16 — 03-30',sort:'2026-02-16',title:'Pixel Peel / Winter Reset campaign',type:'产品 / 治疗方案 campaign',group:'campaign',place:'全球',venue:'Instagram 与线上内容',purpose:'围绕 Alma Hybrid 的两套治疗路径，持续解释患者选择和分层焕肤方案。',desc:'从产品引入、医生决策、病例、前后对比延伸到技术原理，形成"一平台、两种体验"的连续内容。',data:'官网已建立 Pixel Peel 与 Winter Reset 两个品牌化疗程页（Alma Hybrid 平台）；配套 KB 文章《From Procedure to Program》（2026-02-23）。',audience:'皮肤科及医美医生、诊所、潜在患者',result:'连续六周覆盖治疗定位、临床逻辑、病例与技术解释，并导向同主题 webinar。',focus:'Alma 将产品内容做成连续教育路径，而非单条产品科普。',products:'Alma Hybrid · Pixel Peel · Winter Reset',source:'https://www.instagram.com/reel/DUz7Txkk6Kd/',confidence:'B+ · 官方 Instagram + 官网治疗页',image:'assets/pixel.jpg',scale:'全球六周 campaign'},
{id:9,date:'02-23',sort:'2026-02-23',title:'Alma Live Webinar：Pixel Peel / Winter Reset',type:'线上研讨会',group:'webinar',place:'全球线上',venue:'Alma Live Webinar',purpose:'将 Pixel Peel / Winter Reset campaign 延伸为医生可参与的线上临床课程。',desc:'讲解患者选择、治疗时间、方案设计、临床 protocol 与结果。',data:'Prof. Ofir Artzi 主讲（KB 页面 2026-02-25 发布）。',audience:'医生、临床操作人员与 Alma 客户',result:'完成报名传播，并在会后发布专家视频回看。',focus:'短内容负责预热，webinar 负责深度解释，形成内容层级。',products:'Prof. Ofir Artzi · Alma Hybrid',source:'https://almalasers.com/knowledge-booster/pixel-peel-and-winter-reset-on-alma-hybrid/',confidence:'B+ · 官网 KB 页',image:'assets/pixel.jpg',scale:'全球线上课程'},
{id:10,date:'02-27',sort:'2026-02-27',title:'Harmony Bio-Boost 美国发布媒体早餐',type:'产品发布 / 媒体活动',group:'launch',place:'纽约，美国',venue:'Aman New York',purpose:'面向美国美容编辑和 influencer 的新品体验与媒体沟通活动。',desc:'讲解科学原理，并安排 Alma IQ 与 Harmony Bio-Boost 现场体验。',data:'官方 IG 复盘可核：Aman New York 媒体早餐、美国上市发布、Dr. Spero Theodorou 同场、Alma IQ 与 Bio-Boost 现场体验、ELLE / Marie Claire / InStyle / Fashionista 编辑到场。',audience:'ELLE、Marie Claire、InStyle、Fashionista 等美容媒体与 influencer',result:'在纽约完成产品教育、编辑体验和社媒复盘。',focus:'通过高端场地和编辑体验将专业设备转化为媒体选题。',products:'Harmony Bio-Boost · Alma IQ · Dr. Spero Theodorou',source:'https://www.instagram.com/reel/DVQUafdgm38/',confidence:'B+ · 官方 Instagram 活动复盘',image:'assets/imcas.jpg',scale:'美国媒体发布'},
{id:11,date:'03-08',sort:'2026-03-08',title:'International Women’s Day',type:'节日品牌传播',group:'brand',place:'全球',venue:'国际社交媒体',purpose:'围绕国际妇女节表达企业价值观并连接女性员工、伙伴和全球社群。',desc:'发布女性主题品牌内容。',audience:'女性员工、伙伴、客户与社媒关注者',result:'形成单日价值观传播。',focus:'品牌价值内容与产品和专业活动保持适当区分。',products:'Alma 品牌',source:'https://www.instagram.com/p/DVnbzFVDWbj/',confidence:'B · 官方 Instagram',image:'assets/longevityig.jpg',scale:'单日品牌内容'},
{id:12,date:'2026-03',sort:'2026-03-15',title:'Daily Mail：Soprano Titanium 媒体曝光',type:'媒体 PR',group:'pr',place:'英国 / 全球英语市场',venue:'Daily Mail Beauty',purpose:'通过大众媒体的脱毛知识内容带出 Soprano Titanium 产品体验。',desc:'Alma 官网 Newsroom 收录 Daily Mail 脱毛专题文章。',data:'官网 Newsroom 收录页（2026-03-10）标题："Hair Removal Becomes Virtually Painless with Soprano Titanium"，并附 Daily Mail 原文链接。',audience:'英语市场美容消费者与媒体读者',result:'进入 Daily Mail 美容内容，并被 Alma Newsroom 收录。',focus:'媒体报道帮助产品从专业设备语境进入消费者决策语境。',products:'Soprano Titanium',source:'https://almalasers.com/press/hair-removal-becomes-virtually-painless/',confidence:'A · 官网 Newsroom',image:'assets/soprano.jpg',scale:'国际媒体 PR'},
{id:13,date:'03-26',sort:'2026-03-26',title:'Alma Live Webinar：IPL Consistency',type:'线上研讨会 / 学术营销',group:'webinar',place:'全球线上',venue:'Alma Live Webinar',purpose:'面向医生解释 IPL 能量一致性为什么影响安全、治疗窗口和临床结果。',desc:'讲解 IPL 光学、fluence 均匀性、冷却、治疗窗口与近期临床文献。',data:'时长 46 分钟；讲者 Dr. Sharon Jacobi（Alma Director of Clinical Excellence）；KB 页 datePublished 2026-03-30。',audience:'使用或评估 IPL 的医生与临床人员',result:'完成 03-26 直播，并于 04-09 发布官方回看。',focus:'技术主题 webinar 为后续六周 IPL campaign 提供学术基础。',products:'Dr. Sharon Jacobi · Alma Harmony IPL',source:'https://almalasers.com/knowledge-booster/almas-ipl-technology/',confidence:'B+ · 官网 KB 页',image:'assets/imcas-asia.jpg',scale:'全球线上课程'},
{id:14,date:'03-23',sort:'2026-03-23',title:'Inside the Aesthetic Mind：Dr. DongHye Suh',type:'专家内容 / 思想领导',group:'content',place:'全球',venue:'Instagram 专家栏目',purpose:'通过医生专访讨论临床趋势和技术选择，建立专家型内容栏目。',desc:'围绕 RF Plasma、fractional RF、低侵袭和可预测结果展开访谈。',data:'访谈引用两项发表：妊娠纹 RF Plasma + PRP 研究（>71% 观察改善，J Cosmet Laser Ther）；fractional unipolar RF 面部紧致研究（J Cosmet Dermatol）；主张 RF Plasma "color-blind" 降低深肤色 PIH 风险。',audience:'医美医生、临床人员和专业行业受众',result:'发布一篇完整专家观点内容（KB 页 datePublished 2026-03-15）。',focus:'专家观点可为产品传播增加临床判断，而不只是功能介绍。',products:'Dr. DongHye Suh · RF Plasma · fractional RF',source:'https://almalasers.com/knowledge-booster/aesthetic-mind-dr-donghye-suh/',confidence:'B · 官网 KB 页',image:'assets/longevity.jpg',scale:'全球专家内容'},
{id:15,date:'03-26',sort:'2026-03-26',title:'Modern Luxury Angeleno Beauty Issue',type:'媒体 PR',group:'pr',place:'洛杉矶，美国',venue:'Modern Luxury Angeleno',purpose:'借助洛杉矶高端生活方式媒体和行业人物推荐提升产品知名度。',desc:'Nurse Jamie 在 Beauty Issue 中推荐 Alma Harmony 和 Harmony Bio-Boost。',data:'',audience:'洛杉矶高端美容消费者、诊所与行业读者',result:'获得 Beauty Issue 产品推荐并由官方账号转发。',focus:'名人从业者推荐与高端区域媒体结合。',products:'Nurse Jamie · Alma Harmony · Harmony Bio-Boost',source:'https://www.instagram.com/p/DWV26lmjnvy/',confidence:'B · 官方 Instagram 转发',image:'assets/imcas.jpg',scale:'美国区域媒体 PR'},
{id:16,date:'2026-03',sort:'2026-03-28',title:'Marie Claire：Soprano Titanium 媒体曝光',type:'媒体 PR',group:'pr',place:'英国 / 全球英语市场',venue:'Marie Claire UK',purpose:'在比基尼线护理指南中以消费者问题带出专业脱毛技术。',desc:'介绍 ICE Plus 冷却和毛囊靶向等产品卖点。',data:'文章 2026-03-26 刊出，作者 Valeza Bakolli；Shireen Forster（Laser Me Out 创始人）引述"Soprano Titanium 内置 ICE Plus 冷却"；Alma 官网收录于 03-31。',audience:'美容消费者、编辑读者与潜在诊所客户',result:'进入 Marie Claire 护理指南并被 Alma Newsroom 收录。',focus:'通过问题型编辑内容承接消费者搜索与护理需求。',products:'Soprano Titanium · Shireen Forster',source:'https://www.marieclaire.co.uk/beauty/hair/bikini-line-dos-and-donts',confidence:'A · 媒体原文（作者/日期可核）',image:'assets/soprano.jpg',scale:'国际媒体 PR'},
{id:17,date:'04-24 — 04-26',sort:'2026-04-24',title:'Alma Academy Lisbon 2026',type:'自办全球学术峰会 / 战略发布',group:'owned',place:'里斯本，葡萄牙',venue:'Alma Academy Lisbon',purpose:'Alma 年度全球学术旗舰活动，通过专家课程、演示和社交活动连接国际医生与伙伴。',desc:'举办 live demos 与 breakout sessions（Alma Harmony / Hybrid / PrimeX 分组），并发布 Longevity 战略。',data:'新闻稿可核：430 位医生、45 个国家、19 位专家、Longevity 战略发布、live demonstrations，点名讲者 Dr. Spero Theodorou、Prof. Ofir Artzi、Dr. Pablo Naranjo、Dr. Tino Solomon、Dr. Jaerim Kim；breakout sessions 见官方 IG（2026-04-26）；对比上届 Dubrovnik 近 400 医生/46 国。',audience:'全球医生、临床专家、合作伙伴与 Alma 团队',result:'430 医生 / 45 国 / 19 专家参会，并正式发布 Longevity 方向。',focus:'大型 Academy 同时承担学术教育、客户关系和品牌战略发布。',products:'Alma Harmony · Hybrid · PrimeX · Longevity · Eyal Ben David · Prof. Ofir Artzi',source:'https://almalasers.com/press/alma-unveils-longevity-approach-at-alma-academy/',confidence:'A · 官网新闻稿（2026-05-04）',image:'assets/academy.jpg',scale:'全球大型自办峰会'},
{id:18,date:'04-13 — 05-11',sort:'2026-04-13',title:'Alma Harmony IPL Consistency campaign',type:'产品 / 临床证据 campaign',group:'campaign',place:'全球',venue:'Instagram 连续内容',purpose:'围绕 Alma Harmony IPL 的能量一致性和临床可靠性持续开展医生教育。',desc:'连续传播光学设计、均匀 fluence、冷却、临床文献、病例和医师 FAQ。',data:'内容载体为 46 分钟 IPL webinar（Dr. Sharon Jacobi）+ Alma Harmony 产品页。',audience:'皮肤科与医美医生、诊所采购者、临床人员',result:'连续约四周覆盖技术、证据、病例和 7 个专用 applicators。',focus:'以单一技术命题组织多种内容格式，强化产品记忆。',products:'Alma Harmony IPL · 7 个专用 applicators',source:'https://www.instagram.com/reel/DXE6gg1Cc-l/',confidence:'B+ · 官方 Instagram 连续 campaign',image:'assets/imcas-asia.jpg',scale:'全球四周 campaign'},
{id:19,date:'05-07',sort:'2026-05-07',title:'Almarketing Contest 2026',type:'UGC / 伙伴营销',group:'content',place:'全球',venue:'全球伙伴社媒',purpose:'以内容比赛鼓励全球合作伙伴围绕 "Diverse Beauty with Alma" 进行本地创作。',desc:'征集全球伙伴作品并发布前三名及获奖内容。',data:'官方 IG 获奖公告（2026-05-07）：前三名 @torregalsaludyestetica、@avamedical.nordic、@almalasers_italia。',audience:'Alma 全球经销商、诊所伙伴与本地社媒受众',result:'发布 Torre Galsalud y Estética、AVA Medical Nordic、Alma Lasers Italia 三个获奖方。',focus:'UGC 可以扩大总部素材，但应进一步连接专业质量和业务贡献。',products:'Diverse Beauty with Alma · 全球伙伴',source:'https://www.instagram.com/reel/DYCdEoUjrT6/',confidence:'B+ · 官方获奖公告',image:'assets/trends.jpg',scale:'全球伙伴 UGC'},
{id:20,date:'05-14',sort:'2026-05-14',title:'Aesthetic Practitioners / Physicians 致敬传播',type:'节日 / 专业社群品牌传播',group:'brand',place:'全球',venue:'Instagram',purpose:'向一线医生和美学从业者的临床判断、护理与责任致敬。',desc:'发布专业社群品牌内容，强调医护和美学从业者价值。',audience:'医生、美学从业者、诊所团队与合作伙伴',result:'形成单日专业社群互动。',focus:'以专业人群为主角，有助于维护医生关系。',products:'医生与美学从业者',source:'https://www.instagram.com/reel/DYT_vxdjCzQ/',confidence:'B · 官方 Instagram',image:'assets/longevityig.jpg',scale:'单日社群内容'},
{id:21,date:'2026-05',sort:'2026-05-01',title:'BTS 2026',type:'展会 / 学术会议',group:'exhibition',place:'斯德哥尔摩，瑞典',venue:'',purpose:'面向美学专业人士和整形外科医生的北欧专业会议。',desc:'官网活动页确认 Alma 参加 BTS 2026 斯德哥尔摩会议。',data:'官网活动页 meta 描述："Join Alma at BTS, the leading aesthetic professionals and plastic surgeons on May, 2026 in Stockholm."',audience:'美学医生、整形外科医生与北欧诊所客户',result:'官网活动页确认参会（2025-11-20 上线）。',focus:'北欧区域会议有助于深化区域医生和渠道覆盖。',products:'Alma 产品组合',source:'https://almalasers.com/events/bts/',confidence:'A · 官网活动页',image:'assets/bts.jpg',scale:'欧洲区域专业会议'},
{id:22,date:'06-02',sort:'2026-06-02',title:'Pride Month 品牌传播',type:'节日品牌传播',group:'brand',place:'全球',venue:'Instagram',purpose:'围绕多元美、个体故事和自我表达启动 Pride Month 品牌内容。',desc:'使用 #ShowYourColors 发布多元与包容主题。',audience:'全球社群、合作伙伴和消费者',result:'形成 Pride Month 月度主题启动内容。',focus:'价值观传播扩大情感连接，但与临床获客目标不同。',products:'Alma 品牌 · #ShowYourColors',source:'https://www.instagram.com/p/DZFLMgkjftH/',confidence:'B · 官方 Instagram',image:'assets/trends.jpg',scale:'月度品牌主题'},
{id:23,date:'06-19 — 06-21',sort:'2026-06-19',title:'IMCAS Asia 2026',type:'展会 / 学术会议',group:'exhibition',place:'曼谷，泰国',venue:'The Athenee Hotel · Booth #14',purpose:'面向亚洲皮肤科、整形外科和医学美容医生的大型专业会议。',desc:'设置 Booth #14 展位，进行临床交流与技术展示。',data:'官网活动页可核：Booth 14、The Athenee Hotel、2026-06-19~21（页面日历链接 dates=20260619~21）。',audience:'亚洲皮肤科医生、整形外科医生、临床专家与渠道伙伴',result:'完成三日展位展示。',focus:'将国际专家与亚洲本地医生共同放入区域会议议程。',products:'Alma 产品组合',source:'https://almalasers.com/events/imcas-asia/',confidence:'A · 官网活动页',image:'assets/imcas-asia.jpg',scale:'亚洲大型专业展会'},
{id:24,date:'06-25 — 07-01',sort:'2026-06-25',title:'Aesthetic Trends 2026 七日倒计时',type:'趋势内容 campaign',group:'campaign',place:'全球',venue:'Instagram 连续七日',purpose:'用七天倒计时发布年度美学趋势，并为 Longevity 战略进行内容预热。',desc:'每日发布一个趋势：C-Beauty、peptides、medical-grade、hybrid handpieces、skin tightening、emerging markets，最终以 Longevity 收束。',data:'官方 IG 连续七日发布（06-25 起）：Trend #7 C-Beauty → #6 Peptides → #5 Medical-Grade Everything → #4 Hybrid Handpieces → #3 Skin Tightening → #2 Emerging Markets → #1 Longevity；配套 KB 文章《12 Medical Aesthetics Trends for 2026》官网可查。',audience:'医生、诊所经营者、经销商和行业观察者',result:'连续七天发布七个趋势，最终以 Longevity 收束并衔接下一阶段 campaign。',focus:'用趋势内容为品牌战略发布建立市场语境。',products:'Aesthetic Trends · Longevity',source:'https://www.instagram.com/reel/DaA5fRigHCW/',confidence:'B+ · 官方 Instagram 七日连续内容',image:'assets/trends.jpg',scale:'全球七日 campaign'},
{id:25,date:'07-02 — 08-03',sort:'2026-07-02',title:'Alma Longevity 全球思想领导 campaign',type:'品牌战略 / 思想领导 campaign',group:'campaign',place:'全球',venue:'Instagram 与官网',purpose:'围绕"皮肤长期表现"建立新的品牌战略叙事，把单次治疗扩展为长期治疗规划。',desc:'通过宣言、词典、HyGrid、MicroPlasma、全年治疗日历和 FAQ 连续传播。',data:'官方 IG 连载可核：Longevity 宣言（07-02）→ Alma Longevity 词典（07-06）→ HyGrid 技术（07-16）→ MicroPlasma 技术（07-20）→ 全年治疗日历（07-30）→ 医生 FAQ（08-03）；战略发布于 Lisbon Academy（430 医生/45 国/19 专家）；配套 Aging Decoded webinar。',audience:'全球医生、诊所、经销商、行业媒体与患者教育受众',result:'截至 08-03 已形成超过一个月的连续主题内容，并覆盖多个平台和治疗方案。',focus:'Longevity 正成为 Alma 连接产品组合和长期患者管理的总叙事。',products:'Alma Longevity · Harmony · Bio-Boost · Pixel Peel · Winter Reset 等',source:'https://www.instagram.com/reel/DaSz1mViNZM/',confidence:'B+ · 官网新闻稿与官方连续内容',image:'assets/longevityig.jpg',scale:'全球长期战略 campaign'},
{id:26,date:'2026-07',sort:'2026-07-21',title:'Alma Live Webinar：Aging Decoded',type:'线上研讨会 / 思想领导',group:'webinar',place:'全球线上',venue:'Alma Live Webinar',purpose:'用衰老机制框架解释 Alma 产品组合与 Longevity 之间的对应关系。',desc:'按 longevity hallmarks 逐平台解释射频、激光、超声、声能的干预机制，覆盖 neocollagenesis、hormesis、线粒体信号与细胞间通讯。',data:'官方 IG 报名帖（07-21）可核：讲者 Dr. Dean Berman（Alma Global VP of Medical），主题 "The Alma Portfolio, Aging Decoded. How Each Platform Maps to the Hallmarks"，内容含 neocollagenesis、hormesis、mitochondrial signaling、cell-to-cell communication；KB 页 datePublished 2026-07-29。',audience:'医美医生、皮肤科医生和 Alma 平台客户',result:'发布官方报名信息；统计截止时未见公开复盘。',focus:'用基础机制统一解释多产品组合，增强战略叙事一致性。',products:'Dr. Dean Berman · Alma 产品组合',source:'https://almalasers.com/knowledge-booster/aging-decoded-how-each-platform-maps-to-the-hallmarks/',confidence:'B · 官网 KB 页 + 官方 IG',image:'assets/longevity.jpg',scale:'全球线上课程'},
{id:27,date:'07-24',sort:'2026-07-24',title:'Alma Harmony 印度市场发布',type:'产品发布 / 媒体活动',group:'launch',place:'新德里，印度',venue:'独家媒体活动',purpose:'面向印度市场正式介绍 Alma Harmony，并通过医生、专家与媒体现场体验建立本地认知。',desc:'第三方报道确认 Alma 于新德里举办 Alma Harmony 发布活动。',data:'第三方报道可核：新德里、2026-07-24、Alma Harmony 发布、Dr. Rohit Batra（MD Dermaworld Skin and Hair Clinic）引语。',audience:'印度皮肤科与美学医生、行业专家、媒体和潜在客户',result:'第三方报道确认新德里发布活动、现场演示和 Dr. Rohit Batra 等参与。',focus:'新品进入区域市场时同步组织医生与媒体教育。',products:'Alma Harmony · Dr. Rohit Batra',source:'https://www.tripurastarnews.com/alma-lasers-introduces-alma-harmony-in-india-to-expand-advanced-aesthetic-treatment-options/',confidence:'B · 第三方公开报道',image:'assets/imcas-asia.jpg',scale:'印度市场发布'},
{id:28,date:'2026-07',sort:'2026-07-29',title:'Alma 飞顿黑金牛奶光品项赋能峰会',type:'中国市场峰会 / 品项赋能',group:'owned',place:'中国上海',venue:'',purpose:'面向中国机构、医生与行业市场开展黑金牛奶光品项赋能。',desc:'围绕正版设备、品质机构、消费者信任和光电抗衰市场开展行业传播。',data:'第三方微信摘要可核：7 月底的上海，Alma 飞顿「弈定新局·光启新境」黑金牛奶光品项赋能峰会。',audience:'中国合作机构、医生、渠道伙伴和医美行业受众',result:'多个微信公众号在 07-28 至 07-30 报道该峰会。',focus:'这是原表中最重要的中国市场动作，可继续补充官方邀请函、现场图和机构名单。',products:'黑金牛奶光 · 复锐医疗 / Sisram 生态 · 合作机构与医生',source:'https://weixin.sogou.com/weixin?type=2&query=Alma%E9%A3%9E%E9%A1%BF+2026',confidence:'C+ · 微信公开索引',image:'assets/pixel.jpg',scale:'中国市场项目'}
];

const labels={exhibition:'展会 / 会议',owned:'峰会 / 伙伴',webinar:'线上 Webinar',campaign:'主题 Campaign',launch:'发布 / 媒体活动',pr:'媒体 PR',content:'内容 / UGC',brand:'品牌社群'};
let active='all',ascending=true;
const grid=document.querySelector('#activity-grid'),search=document.querySelector('#search'),dialog=document.querySelector('#dialog');
function render(){
 const q=search.value.trim().toLowerCase();
 const list=activities.filter(a=>(active==='all'||a.group===active)&&[a.title,a.place,a.products,a.purpose,a.audience].join(' ').toLowerCase().includes(q)).sort((a,b)=>(ascending?1:-1)*a.sort.localeCompare(b.sort));
 grid.innerHTML=list.map(a=>`<article class="activity-card" tabindex="0" data-id="${a.id}"><div class="card-image ${a.image?'':'placeholder'}" ${a.image?`style="background-image:url('${a.image}')"`:''}><span class="badge">${labels[a.group]}</span><span class="scale-badge">${a.scale}</span></div><div class="card-body"><div class="date-place"><span>${a.date}</span><span>${a.place}</span></div><h3>${a.title}</h3><dl class="facts"><div><dt>活动说明</dt><dd>${a.purpose}</dd></div><div><dt>Alma 动作</dt><dd>${a.desc}</dd></div>${a.data?`<div class="focus"><dt>数据支撑</dt><dd>${a.data}</dd></div>`:''}<div><dt>${a.group==='exhibition'?'参会类型':'主要受众'}</dt><dd>${a.audience}</dd></div><div><dt>公开结果</dt><dd>${a.result}</dd></div><div class="focus"><dt>关注点</dt><dd>${a.focus}</dd></div></dl><div class="card-foot"><span class="products">${a.products}</span><span class="open-icon">↗</span></div></div></article>`).join('');
 document.querySelector('#result-count').textContent=`${list.length} 条记录`;document.querySelector('#empty').style.display=list.length?'none':'block';
}
document.querySelectorAll('.filters button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.filters .active').classList.remove('active');btn.classList.add('active');active=btn.dataset.filter;render()}));
search.addEventListener('input',render);document.querySelector('#sort').addEventListener('click',e=>{ascending=!ascending;e.currentTarget.textContent=`日期：${ascending?'从早到晚':'从晚到早'} ↕`;render()});
function openDetail(id){const a=activities.find(x=>x.id===id);document.querySelector('#dialog-content').innerHTML=`<div class="dialog-inner"><div class="dialog-media" ${a.image?`style="background-image:url('${a.image}')"`:''}></div><div class="dialog-body"><span class="type">${labels[a.group]} · ${a.type}</span><h2>${a.title}</h2><div class="dialog-meta"><div><span>时间</span>${a.date}</div><div><span>地点 / 市场</span>${a.place}</div>${a.venue?`<div><span>会场 / 展位</span>${a.venue}</div>`:''}<div><span>规模</span>${a.scale}</div></div><div class="dialog-detail"><div><span>这个活动是做什么的</span><p>${a.purpose}</p></div><div><span>Alma 开展的内容</span><p>${a.desc}</p></div>${a.data?`<div class="focus"><span>数据支撑</span><p>${a.data}</p></div>`:''}<div><span>受众 / 参会类型</span><p>${a.audience}</p></div><div><span>公开结果</span><p>${a.result}</p></div><div class="focus"><span>竞争关注点</span><p>${a.focus}</p></div></div><div class="dialog-products"><strong>重点产品 / 人物</strong><br>${a.products}</div><a class="dialog-source" href="${a.source}" target="_blank" rel="noreferrer">查看来源 <span>↗</span></a><p class="confidence">${a.confidence}</p></div></div>`;dialog.showModal()}
grid.addEventListener('click',e=>{const card=e.target.closest('.activity-card');if(card)openDetail(Number(card.dataset.id))});grid.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.activity-card'))openDetail(Number(e.target.dataset.id))});document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});render();
